[platformio]
default_envs = arduino_uno, arduino_mega, esp32, esp8266
src_dir      = test/test_ram

[env:arduino_uno]
platform    = atmelavr
board       = uno
framework   = arduino
lib_extra_dirs = .
build_flags = -Os -Wall

[env:arduino_mega]
platform    = atmelavr
board       = megaatmega2560
framework   = arduino
lib_extra_dirs = .
build_flags = -Os -Wall

[env:esp32]
platform    = espressif32
board       = esp32dev
framework   = arduino
lib_extra_dirs = .
build_flags = -Os

[env:esp8266]
platform    = espressif8266
board       = nodemcuv2
framework   = arduino
lib_extra_dirs = .
build_flags = -Os
